[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_rounds = 200
fs_permissions = [{ access = "read", path = "./broadcast" }]


[lint]
exclude_lints = ["mixed-case-variable", "screaming-snake-case-immutable"]
ignore = ["test/**/*"]


[fuzz]
runs = 10000

[invariant]
runs = 128
depth = 128
fail_on_revert = true